name: Continuous Deployment workflow

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use SSH Key
        run: |
            mkdir -p ~/.ssh/
            echo "${{secrets.SECRET}}" > ~/.ssh/id_rsa
            sudo chmod 600 ~/.ssh/id_rsa
      - name: Configure Git
        run: |
              git config --global user.email "cd-user@cd-user.com"
              git config --global user.name "cd-user"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy -- -r git@github.com:Faq-ndo/gh-pages-automatic.git