name: Continuous Deployment workflow

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Configure Git
        run: |
          git config --global user.email "facundodenardo@gmail.com.com"
          git config --global user.name "Faq-ndo"
      - name: Deploy
        run: npm run deploy